name: github-actions-demo
on: [push]
jobs:
  build_cml:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Regression on Tesla stock
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          # Run main
          python main.py

          # Add text
          echo "## Fit Summary" > reports.md
          cat ./out/fit_summary.txt >> reports.md

          # Adding graphs
          echo "## Correlation Matrix" >> reports.md

          # Send the report!
          cml-send-comment reports.md
